apiVersion: apps/v1
kind: Deployment
metadata:
  name: xuanwu-agent
  namespace: xuanwu-agent
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: xuanwu-agent
  template:
    metadata:
      labels:
        app: xuanwu-agent
    spec:
      containers:
        - name: xuanwu-agent
          image: swr.cn-east-3.myhuaweicloud.com/turingsyn/xuanwu-agent:48dae05
          ports:
            - containerPort: 8000
          env:
            - name: LISTEN_ADDRESS
              value: 127.0.0.1:8000
          command:
            - /app/xuanwu-agent
            - ts-agent --address $LISTEN_ADDRESS
      imagePullSecrets:
        - name: huawei-swr

